name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest #${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Clean build folder
      run: rm -rf ${{ github.workspace }}/build

    - name: Set build directory
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Clone Pico SDK
      run: git clone -b master https://github.com/raspberrypi/pico-sdk.git ${{ github.workspace }}/pico-sdk

    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0-dev
        
    - name: set env vars (Linux)
      run: |
        echo "PICO_SDK_PATH=${{ github.workspace }}/pico-sdk" >> $GITHUB_ENV
        echo "PICO_TOOLCHAIN_PATH=/usr/bin/" >> $GITHUB_ENV
      
    - name: Configure CMake (Linux)
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -DPICO_BOARD=pico2
        -G Ninja
        -S ${{ github.workspace }}/Mgs_project_CICD_TDD

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} #--config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest -C Release #--build-config ${{ matrix.build_type }}

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: pico2-firmware
        path: ${{ steps.strings.outputs.build-output-dir }}/*.uf2
