name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Mgs_project_CICD_TDD/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Mgs_project_CICD_TDD/**'

jobs:
  host-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++

      - name: Configure CMake (host build)
        run: cmake -B build-host -DHOST_BUILD=ON -G Ninja -S Mgs_project_CICD_TDD

      - name: Build tests
        run: cmake --build build-host

      - name: Run tests
        working-directory: build-host
        run: ctest -V

  build:
    needs: host-tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Clean build folder (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: rm -rf ${{ github.workspace }}/build-target

      - name: Clean build folder (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: Remove-Item -Recurse -Force ${{ github.workspace }}\build-target -ErrorAction SilentlyContinue
      
      - name: Set build directory
        id: strings
        shell: bash
        run: echo "build-output-dir=${{ github.workspace }}/build-target" >> "$GITHUB_OUTPUT"

      - name: Clone Pico SDK
        run: git clone -b master https://github.com/raspberrypi/pico-sdk.git ${{ github.workspace }}/pico-sdk

      # --- Linux ---
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0-dev
          
      - name: set env vars (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "PICO_SDK_PATH=${{ github.workspace }}/pico-sdk" >> $GITHUB_ENV
          echo "PICO_TOOLCHAIN_PATH=/usr/bin/" >> $GITHUB_ENV

      # --- Windows ---
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake ninja -y
          choco install gcc-arm-embedded -y

      - name: Set PICO_TOOLCHAIN_PATH (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $gccPath = (Get-Command arm-none-eabi-gcc).Source
          $gccDir = Split-Path $gccPath
          echo "PICO_TOOLCHAIN_PATH=$gccDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PICO_SDK_PATH=${{ github.workspace }}\pico-sdk" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # --- Build Firmware ---
      - name: Configure CMake
        run: cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DPICO_BOARD=rb2350 \
          -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
          -DCMAKE_CXX_COMPILER=arm-none-eabi-g++ \
          -G Ninja \
          -S ${{ github.workspace }}/Mgs_project_CICD_TDD

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico2-firmware-${{ matrix.os }}
          path: ${{ steps.strings.outputs.build-output-dir }}/*.uf2
        
  deploy-windows:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: pico2-firmware-windows-latest 

      - name: Flash Pico
        run: |
          copy *.uf2 D:\
