name: CMake on Linux - Pico

on:
  push:
    branches: [ "experimental/modbus" ]
    paths:
      - 'modbus/**'
  pull_request:
    branches: [ "experimental/modbus" ]
    paths:
      - 'modbus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Clean build folder
        run: rm -rf ${{ github.workspace }}/build-target

      - name: Set build directory
        id: strings
        shell: bash
        run: echo "build-output-dir=${{ github.workspace }}/build-target" >> "$GITHUB_OUTPUT"

      - name: Clone Pico SDK
        run: git clone -b master https://github.com/raspberrypi/pico-sdk.git ${{ github.workspace }}/pico-sdk

      - name: Install firmware dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build libusb-1.0-0-dev wget tar
          wget https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz
          sudo mkdir -p /opt/arm-gnu-toolchain
          sudo tar -xvf arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz -C /opt/arm-gnu-toolchain --strip-components=1
          echo "/opt/arm-gnu-toolchain/bin" >> $GITHUB_PATH
          echo "PICO_TOOLCHAIN_PATH=/opt/arm-gnu-toolchain/bin" >> $GITHUB_ENV
          echo "PICO_SDK_PATH=${{ github.workspace }}/pico-sdk" >> $GITHUB_ENV


      - name: Configure CMake
        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DPICO_BOARD=pico2 \
            -DHOST_BUILD=OFF \
            -DCMAKE_TOOLCHAIN_FILE=$PICO_SDK_PATH/pico_sdk_import.cmake \
            -G Ninja \
            -S ${{ github.workspace }}/Mgs_project_CICD_TDD

      - name: Build firmware
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico2-firmware-linux
          path: ${{ steps.strings.outputs.build-output-dir }}/*.uf2
